name:                declduino
version:             0.1.0.0
github:              "t4ccer/declduino"
license:             BSD3
author:              "t4ccer"
maintainer:          "t4ccer@gmail.com"
copyright:           "t4ccer"

extra-source-files:
- README.md


description:         Please see the README on GitHub at <https://github.com/t4ccer/declduino#readme>

dependencies:
- base >= 4.14.0 && < 4.14.1
- yaml
- text >= 1.2.3.2
- bytestring
- cmdargs
- ardu-gen
- transformers
- aeson
library:
  source-dirs: src

executables:
  declduino:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fwarn-incomplete-patterns
    dependencies:
    - declduino
